services:
  - type: web
    name: converter-x-api
    runtime: python
    buildCommand: |
      apt-get update && apt-get install -y ffmpeg
      pip install -r requirements.txt
    startCommand: gunicorn server:app --timeout 300 --workers 2
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
    disk:
      name: tmp-storage
      mountPath: /tmp
      sizeGB: 1